"""
Script to generate a standalone, Colab Pro ready Jupyter Notebook for Phase 2.
"""

import json
import os


def create_colab_notebook(output_path: str = "notebooks/train_baseline_colab.ipynb"):
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# SIH26012 — AI-Based Automated Urban Parcel Mapping\n",
                "## Phase 2: Fast Baseline Cadastral Segmentation Model\n",
                "\n",
                "This notebook trains and evaluates the baseline lightweight Residual U-Net segmentation model on 512×512 CadastreVision aerial imagery patches using a combined Focal + Dice loss with PyTorch AMP mixed precision."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Install & Import Dependencies\n",
                "!pip install -q rasterio geopandas shapely pyogrio opencv-python-headless matplotlib pillow pyyaml tqdm\n",
                "\n",
                "import os, sys, time, json, random\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "from PIL import Image\n",
                "import matplotlib.pyplot as plt\n",
                "from tqdm import tqdm\n",
                "\n",
                "import torch\n",
                "import torch.nn as nn\n",
                "import torch.nn.functional as F\n",
                "from torch.utils.data import Dataset, DataLoader\n",
                "\n",
                "print(f\"PyTorch Version: {torch.__version__}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2 & 3. GPU Detection and Hardware Info\n",
                "device = torch.device(\"cuda\" if torch.cuda.is_available() else (\"mps\" if hasattr(torch.backends, \"mps\") and torch.backends.mps.is_available() else \"cpu\"))\n",
                "print(f\"Active Compute Device: {device}\")\n",
                "\n",
                "if device.type == \"cuda\":\n",
                "    print(f\"GPU Name: {torch.cuda.get_device_name(0)}\")\n",
                "    print(f\"Total VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB\")\n",
                "    print(f\"CUDA Capability: {torch.cuda.get_device_capability(0)}\")\n",
                "    torch.backends.cudnn.benchmark = True"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 4 & 5. Locate Dataset and Inspect Metadata Catalogs\n",
                "BASE_DIR = \".\" if os.path.exists(\"data\") else \"/content/SIH26012\"\n",
                "PROCESSED_DIR = os.path.join(BASE_DIR, \"data/processed\")\n",
                "METADATA_DIR = os.path.join(PROCESSED_DIR, \"metadata\")\n",
                "\n",
                "df_train = pd.read_csv(os.path.join(METADATA_DIR, \"patches_train.csv\"))\n",
                "df_val = pd.read_csv(os.path.join(METADATA_DIR, \"patches_val.csv\"))\n",
                "df_test = pd.read_csv(os.path.join(METADATA_DIR, \"patches_test.csv\"))\n",
                "\n",
                "print(f\"Train Patches: {len(df_train)} (from {df_train['source_tiff'].nunique()} tiles)\")\n",
                "print(f\"Val Patches:   {len(df_val)} (from {df_val['source_tiff'].nunique()} tiles)\")\n",
                "print(f\"Test Patches:  {len(df_test)} (from {df_test['source_tiff'].nunique()} tiles)\")\n",
                "print(f\"Useful boundary patch ratio (Train): {(df_train['boundary_pixels'] >= 50).mean()*100:.1f}%\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 6. Data Augmentations and PyTorch Dataset Definition\n",
                "class CadastreAugmentation:\n",
                "    def __init__(self, is_train=True):\n",
                "        self.is_train = is_train\n",
                "    def __call__(self, img_np, mask_np):\n",
                "        img = img_np.astype(np.float32) / 255.0\n",
                "        m = mask_np.astype(np.float32)\n",
                "        if len(m.shape) == 2:\n",
                "            m = np.expand_dims(m, axis=-1)\n",
                "        if self.is_train:\n",
                "            if random.random() < 0.5:\n",
                "                img, m = np.fliplr(img).copy(), np.fliplr(m).copy()\n",
                "            if random.random() < 0.5:\n",
                "                img, m = np.flipud(img).copy(), np.flipud(m).copy()\n",
                "            if random.random() < 0.5:\n",
                "                k = random.randint(1, 3)\n",
                "                img, m = np.rot90(img, k=k, axes=(0, 1)).copy(), np.rot90(m, k=k, axes=(0, 1)).copy()\n",
                "            if random.random() < 0.3:\n",
                "                alpha = 1.0 + random.uniform(-0.15, 0.15)\n",
                "                beta = random.uniform(-0.15, 0.15)\n",
                "                img = np.clip(alpha * img + beta, 0.0, 1.0)\n",
                "        return torch.from_numpy(np.transpose(img, (2, 0, 1))).float(), torch.from_numpy(np.transpose(m, (2, 0, 1))).float()\n",
                "\n",
                "class CadastreDataset(Dataset):\n",
                "    def __init__(self, df, processed_dir, transform=None, max_samples=None):\n",
                "        self.df = df.sample(n=max_samples, random_state=42).reset_index(drop=True) if max_samples else df\n",
                "        self.processed_dir = processed_dir\n",
                "        self.transform = transform\n",
                "    def __len__(self):\n",
                "        return len(self.df)\n",
                "    def __getitem__(self, idx):\n",
                "        row = self.df.iloc[idx]\n",
                "        img = np.array(Image.open(os.path.join(self.processed_dir, row[\"image_path\"])).convert(\"RGB\"))\n",
                "        mask = np.array(Image.open(os.path.join(self.processed_dir, row[\"mask_path\"])).convert(\"L\"))\n",
                "        img_t, mask_t = self.transform(img, mask) if self.transform else (\n",
                "            torch.from_numpy(np.transpose(img.astype(np.float32)/255.0, (2, 0, 1))).float(),\n",
                "            torch.from_numpy(mask.astype(np.float32)).unsqueeze(0).float()\n",
                "        )\n",
                "        return {\"image\": img_t, \"mask\": mask_t, \"patch_id\": row[\"patch_id\"]}"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 7. DataLoaders Construction\n",
                "BATCH_SIZE = 16 if device.type == \"cuda\" else 8\n",
                "NUM_WORKERS = 4 if device.type == \"cuda\" else 0\n",
                "PIN_MEMORY = True if device.type == \"cuda\" else False\n",
                "\n",
                "train_dataset = CadastreDataset(df_train, PROCESSED_DIR, transform=CadastreAugmentation(is_train=True))\n",
                "val_dataset = CadastreDataset(df_val, PROCESSED_DIR, transform=CadastreAugmentation(is_train=False))\n",
                "test_dataset = CadastreDataset(df_test, PROCESSED_DIR, transform=CadastreAugmentation(is_train=False))\n",
                "\n",
                "train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY, drop_last=True)\n",
                "val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY)\n",
                "test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY)\n",
                "\n",
                "print(f\"Batches per epoch: Train={len(train_loader)}, Val={len(val_loader)}, Test={len(test_loader)}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 8. Lightweight Residual U-Net Architecture\n",
                "class DoubleConv(nn.Module):\n",
                "    def __init__(self, in_ch, out_ch, residual=True):\n",
                "        super().__init__()\n",
                "        self.residual = residual\n",
                "        self.conv = nn.Sequential(\n",
                "            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False), nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True),\n",
                "            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False), nn.BatchNorm2d(out_ch)\n",
                "        )\n",
                "        self.shortcut = nn.Sequential(nn.Conv2d(in_ch, out_ch, 1, bias=False), nn.BatchNorm2d(out_ch)) if (residual and in_ch != out_ch) else nn.Identity()\n",
                "    def forward(self, x):\n",
                "        return F.relu(self.conv(x) + (self.shortcut(x) if self.residual else 0), inplace=True)\n",
                "\n",
                "class CadastreUNet(nn.Module):\n",
                "    def __init__(self, in_channels=3, out_channels=1, features=[32, 64, 128, 256, 512]):\n",
                "        super().__init__()\n",
                "        f = features\n",
                "        self.inc = DoubleConv(in_channels, f[0])\n",
                "        self.down1 = nn.Sequential(nn.MaxPool2d(2), DoubleConv(f[0], f[1]))\n",
                "        self.down2 = nn.Sequential(nn.MaxPool2d(2), DoubleConv(f[1], f[2]))\n",
                "        self.down3 = nn.Sequential(nn.MaxPool2d(2), DoubleConv(f[2], f[3]))\n",
                "        self.down4 = nn.Sequential(nn.MaxPool2d(2), DoubleConv(f[3], f[4]))\n",
                "        self.up1 = nn.ConvTranspose2d(f[4], f[3], 2, stride=2)\n",
                "        self.conv1 = DoubleConv(f[4], f[3])\n",
                "        self.up2 = nn.ConvTranspose2d(f[3], f[2], 2, stride=2)\n",
                "        self.conv2 = DoubleConv(f[3], f[2])\n",
                "        self.up3 = nn.ConvTranspose2d(f[2], f[1], 2, stride=2)\n",
                "        self.conv3 = DoubleConv(f[2], f[1])\n",
                "        self.up4 = nn.ConvTranspose2d(f[1], f[0], 2, stride=2)\n",
                "        self.conv4 = DoubleConv(f[1], f[0])\n",
                "        self.outc = nn.Conv2d(f[0], out_channels, 1)\n",
                "    def forward(self, x):\n",
                "        x1 = self.inc(x)\n",
                "        x2 = self.down1(x1)\n",
                "        x3 = self.down2(x2)\n",
                "        x4 = self.down3(x3)\n",
                "        x5 = self.down4(x4)\n",
                "        x = self.conv1(torch.cat([x4, self.up1(x5)], dim=1))\n",
                "        x = self.conv2(torch.cat([x3, self.up2(x)], dim=1))\n",
                "        x = self.conv3(torch.cat([x2, self.up3(x)], dim=1))\n",
                "        x = self.conv4(torch.cat([x1, self.up4(x)], dim=1))\n",
                "        return torch.sigmoid(self.outc(x))\n",
                "\n",
                "model = CadastreUNet().to(device)\n",
                "total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)\n",
                "print(f\"Initialized CadastreUNet with {total_params:,} trainable parameters.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Combined Focal + Dice Loss\n",
                "class CombinedFocalDiceLoss(nn.Module):\n",
                "    def __init__(self, focal_w=0.5, dice_w=0.5, alpha=0.25, gamma=2.0, smooth=1.0):\n",
                "        super().__init__()\n",
                "        self.focal_w, self.dice_w, self.alpha, self.gamma, self.smooth = focal_w, dice_w, alpha, gamma, smooth\n",
                "    def forward(self, pred, target):\n",
                "        pred_c = torch.clamp(pred, 1e-7, 1.0 - 1e-7)\n",
                "        pt = torch.where(target == 1.0, pred_c, 1.0 - pred_c)\n",
                "        at = torch.where(target == 1.0, self.alpha, 1.0 - self.alpha)\n",
                "        focal = (-at * torch.pow(1.0 - pt, self.gamma) * torch.log(pt)).mean()\n",
                "        p_flat, t_flat = pred.view(pred.size(0), -1), target.view(target.size(0), -1)\n",
                "        dice = (1.0 - (2.0 * (p_flat * t_flat).sum(1) + self.smooth) / (p_flat.sum(1) + t_flat.sum(1) + self.smooth)).mean()\n",
                "        return self.focal_w * focal + self.dice_w * dice\n",
                "\n",
                "criterion = CombinedFocalDiceLoss().to(device)\n",
                "optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)\n",
                "scaler = torch.cuda.amp.GradScaler() if device.type == \"cuda\" else None\n",
                "print(\"Loss and Optimizer ready.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 9. Mandatory Sanity Check (1-2 fast epochs on small subset)\n",
                "print(\"--- Starting Sanity Check ---\")\n",
                "sanity_ds = CadastreDataset(df_train, PROCESSED_DIR, transform=CadastreAugmentation(is_train=True), max_samples=64)\n",
                "sanity_loader = DataLoader(sanity_ds, batch_size=8, shuffle=True)\n",
                "\n",
                "model.train()\n",
                "for s_epoch in range(1, 3):\n",
                "    s_loss = 0.0\n",
                "    for batch in sanity_loader:\n",
                "        imgs, masks = batch[\"image\"].to(device), batch[\"mask\"].to(device)\n",
                "        optimizer.zero_grad()\n",
                "        preds = model(imgs)\n",
                "        loss = criterion(preds, masks)\n",
                "        loss.backward()\n",
                "        optimizer.step()\n",
                "        s_loss += loss.item()\n",
                "    print(f\"Sanity Epoch {s_epoch}: Avg Loss = {s_loss / len(sanity_loader):.4f}\")\n",
                "print(\"Sanity Check PASSED! Forward pass, gradient flow, and loss reduction verified.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 10, 11, 12. Full Baseline Model Training & Validation Loop\n",
                "EPOCHS = 15\n",
                "PATIENCE = 3\n",
                "best_val_f1 = -1.0\n",
                "patience_counter = 0\n",
                "os.makedirs(\"checkpoints\", exist_ok=True)\n",
                "\n",
                "history = {\"train_loss\": [], \"train_f1\": [], \"val_loss\": [], \"val_f1\": [], \"val_iou\": [], \"val_prec\": [], \"val_rec\": []}\n",
                "scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS, eta_min=1e-6)\n",
                "\n",
                "def evaluate(loader):\n",
                "    model.eval()\n",
                "    tot_loss, tp, fp, fn, tn = 0.0, 0, 0, 0, 0\n",
                "    with torch.no_grad():\n",
                "        for batch in loader:\n",
                "            imgs, masks = batch[\"image\"].to(device), batch[\"mask\"].to(device)\n",
                "            preds = model(imgs)\n",
                "            tot_loss += criterion(preds, masks).item() * imgs.size(0)\n",
                "            p_bin, g_bin = (preds >= 0.5).cpu().numpy().astype(np.uint8), (masks > 0.5).cpu().numpy().astype(np.uint8)\n",
                "            tp += int(((p_bin == 1) & (g_bin == 1)).sum())\n",
                "            fp += int(((p_bin == 1) & (g_bin == 0)).sum())\n",
                "            fn += int(((p_bin == 0) & (g_bin == 1)).sum())\n",
                "            tn += int(((p_bin == 0) & (g_bin == 0)).sum())\n",
                "    eps = 1e-7\n",
                "    prec = tp / (tp + fp + eps)\n",
                "    rec = tp / (tp + fn + eps)\n",
                "    f1 = 2.0 * tp / (2.0 * tp + fp + fn + eps)\n",
                "    iou = tp / (tp + fp + fn + eps)\n",
                "    return tot_loss / len(loader.dataset), prec, rec, f1, iou\n",
                "\n",
                "print(f\"Training Baseline U-Net for {EPOCHS} epochs...\")\n",
                "start_time = time.time()\n",
                "for epoch in range(1, EPOCHS + 1):\n",
                "    ep_start = time.time()\n",
                "    model.train()\n",
                "    train_loss = 0.0\n",
                "    for batch in tqdm(train_loader, desc=f\"Epoch {epoch:02d}/{EPOCHS}\"):\n",
                "        imgs, masks = batch[\"image\"].to(device), batch[\"mask\"].to(device)\n",
                "        optimizer.zero_grad()\n",
                "        if scaler:\n",
                "            with torch.cuda.amp.autocast():\n",
                "                preds = model(imgs)\n",
                "                loss = criterion(preds, masks)\n",
                "            scaler.scale(loss).backward()\n",
                "            scaler.step(optimizer)\n",
                "            scaler.update()\n",
                "        else:\n",
                "            preds = model(imgs)\n",
                "            loss = criterion(preds, masks)\n",
                "            loss.backward()\n",
                "            optimizer.step()\n",
                "        train_loss += loss.item() * imgs.size(0)\n",
                "    \n",
                "    train_loss /= len(train_loader.dataset)\n",
                "    val_loss, val_prec, val_rec, val_f1, val_iou = evaluate(val_loader)\n",
                "    scheduler.step()\n",
                "    \n",
                "    history[\"train_loss\"].append(train_loss)\n",
                "    history[\"val_loss\"].append(val_loss)\n",
                "    history[\"val_f1\"].append(val_f1)\n",
                "    history[\"val_iou\"].append(val_iou)\n",
                "    history[\"val_prec\"].append(val_prec)\n",
                "    history[\"val_rec\"].append(val_rec)\n",
                "    \n",
                "    print(f\"Epoch {epoch:02d} | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | Val F1: {val_f1:.4f} | IoU: {val_iou:.4f} | Prec: {val_prec:.4f} | Rec: {val_rec:.4f} | Time: {time.time()-ep_start:.1f}s\")\n",
                "    \n",
                "    if val_f1 > best_val_f1:\n",
                "        best_val_f1 = val_f1\n",
                "        patience_counter = 0\n",
                "        torch.save(model.state_dict(), \"checkpoints/best_model.pth\")\n",
                "        print(f\"  >>> ⭐ Best checkpoint saved! (Val F1: {val_f1:.4f})\")\n",
                "    else:\n",
                "        patience_counter += 1\n",
                "        if patience_counter >= PATIENCE:\n",
                "            print(f\"Early stopping triggered at epoch {epoch}.\")\n",
                "            break\n",
                "\n",
                "print(f\"Training finished in {time.time()-start_time:.1f}s. Best Val F1: {best_val_f1:.4f}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 13 & 14. Evaluate Best Model on Test Split\n",
                "model.load_state_dict(torch.load(\"checkpoints/best_model.pth\", map_location=device))\n",
                "test_loss, test_prec, test_rec, test_f1, test_iou = evaluate(test_loader)\n",
                "\n",
                "print(\"==================================================\")\n",
                "print(\" FINAL TEST EVALUATION RESULTS\")\n",
                "print(\"==================================================\")\n",
                "print(f\"Test Loss:      {test_loss:.4f}\")\n",
                "print(f\"Test F1 / Dice: {test_f1:.4f}\")\n",
                "print(f\"Test IoU:       {test_iou:.4f}\")\n",
                "print(f\"Test Precision: {test_prec:.4f}\")\n",
                "print(f\"Test Recall:    {test_rec:.4f}\")\n",
                "print(\"==================================================\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 15. Generate 5-Panel Prediction Visualizations\n",
                "model.eval()\n",
                "os.makedirs(\"predictions\", exist_ok=True)\n",
                "\n",
                "sample_batch = next(iter(test_loader))\n",
                "imgs, masks, p_ids = sample_batch[\"image\"].to(device), sample_batch[\"mask\"].to(device), sample_batch[\"patch_id\"]\n",
                "\n",
                "with torch.no_grad():\n",
                "    preds = model(imgs)\n",
                "\n",
                "for i in range(min(4, imgs.size(0))):\n",
                "    img_np = (imgs[i].permute(1, 2, 0).cpu().numpy() * 255).astype(np.uint8)\n",
                "    gt_np = masks[i, 0].cpu().numpy()\n",
                "    pred_p = preds[i, 0].cpu().numpy()\n",
                "    pred_b = (pred_p >= 0.5).astype(np.uint8)\n",
                "    \n",
                "    # Overlay\n",
                "    overlay = img_np.copy().astype(np.float32)\n",
                "    tp_m = (gt_np > 0.5) & (pred_b == 1)\n",
                "    fp_m = (gt_np <= 0.5) & (pred_b == 1)\n",
                "    fn_m = (gt_np > 0.5) & (pred_b == 0)\n",
                "    overlay[tp_m] = 0.4 * overlay[tp_m] + 0.6 * np.array([255, 255, 0]) # Yellow = TP\n",
                "    overlay[fp_m] = 0.4 * overlay[fp_m] + 0.6 * np.array([255, 50, 50])  # Red = FP\n",
                "    overlay[fn_m] = 0.4 * overlay[fn_m] + 0.6 * np.array([50, 200, 50])  # Green = FN\n",
                "    overlay = np.clip(overlay, 0, 255).astype(np.uint8)\n",
                "    \n",
                "    fig, axes = plt.subplots(1, 5, figsize=(22, 5), dpi=120)\n",
                "    axes[0].imshow(img_np); axes[0].set_title(\"1. Aerial Image\"); axes[0].axis(\"off\")\n",
                "    axes[1].imshow(gt_np, cmap=\"gray\"); axes[1].set_title(\"2. Ground Truth\"); axes[1].axis(\"off\")\n",
                "    axes[2].imshow(pred_p, cmap=\"magma\", vmin=0, vmax=1); axes[2].set_title(\"3. Probability Map\"); axes[2].axis(\"off\")\n",
                "    axes[3].imshow(pred_b, cmap=\"gray\"); axes[3].set_title(\"4. Binary Prediction\"); axes[3].axis(\"off\")\n",
                "    axes[4].imshow(overlay); axes[4].set_title(\"5. Overlay (Y=TP, R=FP, G=FN)\"); axes[4].axis(\"off\")\n",
                "    plt.suptitle(f\"Cadastral Boundary Prediction — {p_ids[i]}\", fontsize=14, fontweight=\"bold\")\n",
                "    plt.tight_layout()\n",
                "    out_p = f\"predictions/sample_pred_{i+1}_{p_ids[i]}.png\"\n",
                "    plt.savefig(out_p)\n",
                "    plt.show()\n",
                "    print(f\"Saved prediction visualizer: {out_p}\")"
            ]
        }
    ]

    notebook = {
        "cells": cells,
        "metadata": {
            "accelerator": "GPU",
            "colab": {"provenance": []},
            "language_info": {"name": "python", "version": "3.10"},
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}
        },
        "nbformat": 4,
        "nbformat_minor": 0
    }

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(notebook, f, indent=2)
    print(f"Generated Colab notebook: {output_path} ({len(cells)} cells)")


if __name__ == "__main__":
    create_colab_notebook()
